# Generated by Django 3.2.6 on 2023-02-14 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exame', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('cod_exame', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('qtd_questoes', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='questao',
            name='cod_questao',
        ),
        migrations.AddField(
            model_name='questao',
            name='cod_exame',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='exame.exame'),
            preserve_default=False,
        ),
    ]
