# Generated by Django 3.2.6 on 2023-02-14 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exame', '0002_auto_20230214_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exame',
            name='cod_exame',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
